db.url=jdbc:postgresql://ep-sparkling-river-ahs28is5-pooler.c-3.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_LAqiJ7Q5Vyeh&sslmode=require&channelBinding=require
db.username=neondb_owner
db.password=npg_4k5cQrlVpBfg

cloudinary.cloud_name=dtd3yzllq
cloudinary.api_key=497371725786935
cloudinary.api_secret=_eBOJdVHm70IOUtqJbjOyl8y-kU
