db.url=jdbc:postgresql://ep-dawn-dream-a4dqe0fw-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
db.username=neondb_owner
db.password=npg_4k5cQrlVpBfg

cloudinary.cloud_name=dtd3yzllq
cloudinary.api_key=497371725786935
cloudinary.api_secret=_eBOJdVHm70IOUtqJbjOyl8y-kU